package quina.jdbc;

import java.sql.SQLException;
import java.sql.Statement;

import quina.annotation.proxy.ProxyInitialSetting;
import quina.annotation.proxy.ProxyInjectMethod;
import quina.annotation.proxy.ProxyOverride;
import quina.util.Flag;

/**
 * AbstractProxyStatement.
 */
public abstract class AbstractQuinaProxyStatement
	implements Statement {
	
	/**
	 * ProxyConnection.
	 */
	protected QuinaProxyConnection connection;
	
	/**
	 * クローズフラグ.
	 */
	protected Flag closeFlag = new Flag(true);
	
	/**
	 * Statementを取得.
	 * @return Statement 対象のステートメントが返却されます.
	 */
	protected abstract Statement getStatement();
	
	/**
	 * Statementを設定.
	 * @param s 対象のステートメントを設定します
	 */
	protected abstract void setStatement(Statement s);
	
	/**
	 * 初期設定.
	 * @param connection ProxyConnectionを設定します.
	 * @param statement 元のStatementを設定します.
	 */
	@ProxyInitialSetting
	protected void setting(QuinaProxyConnection connection,
		Statement statement) {
		if(connection == null || statement == null) {
			throw new NullPointerException();
		}
		this.connection = connection;
		setStatement(statement);
		this.closeFlag.set(false);
	}
	
	@ProxyInjectMethod
	protected void checkClose() throws SQLException {
		if(isClosed()) {
			throw new SQLException("It's already closed.");
		}
	}
	
	@Override
	@ProxyOverride
	public void close() throws SQLException {
		if(closeFlag.setToGetBefore(true)) {
			return;
		}
		final Statement s = getStatement();
		setStatement(null);
		if(s != null) {
			s.close();
		}
	}

	@Override
	@ProxyOverride
	public boolean isClosed() throws SQLException {
		if(closeFlag.get()) {
			return true;
		}
		final Statement s = getStatement();
		return s == null ? true : s.isClosed();
	}

	@Override
	@ProxyOverride
	public QuinaProxyResultSet executeQuery(String sql)
		throws SQLException {
		checkClose();
		return QuinaProxyUtil.getResultSet(this,
			getStatement().executeQuery(
			connection.getSQL(sql)));
	}

	@Override
	@ProxyOverride
	public int executeUpdate(String sql)
		throws SQLException {
		checkClose();
		return getStatement().executeUpdate(
			connection.getSQL(sql));
	}
	
	@Override
	@ProxyOverride
	public boolean execute(String sql)
		throws SQLException {
		checkClose();
		return getStatement().execute(
			connection.getSQL(sql));
	}
	
	@Override
	@ProxyOverride
	public void addBatch(String sql)
		throws SQLException {
		checkClose();
		getStatement().addBatch(
			connection.getSQL(sql));
	}
	
	@Override
	@ProxyOverride
	public int executeUpdate(String sql, int autoGeneratedKeys)
		throws SQLException {
		checkClose();
		return getStatement().executeUpdate(
			connection.getSQL(sql), autoGeneratedKeys);
	}

	@Override
	@ProxyOverride
	public int executeUpdate(String sql, int[] columnIndexes)
		throws SQLException {
		checkClose();
		return getStatement().executeUpdate(
			connection.getSQL(sql), columnIndexes);
	}

	@Override
	@ProxyOverride
	public int executeUpdate(String sql, String[] columnNames)
		throws SQLException {
		checkClose();
		return getStatement().executeUpdate(
			connection.getSQL(sql), columnNames);
	}

	@Override
	@ProxyOverride
	public boolean execute(String sql, int autoGeneratedKeys)
		throws SQLException {
		checkClose();
		return getStatement().execute(
			connection.getSQL(sql), autoGeneratedKeys);
	}

	@Override
	@ProxyOverride
	public boolean execute(String sql, int[] columnIndexes)
		throws SQLException {
		checkClose();
		return getStatement().execute(
			connection.getSQL(sql), columnIndexes);
	}

	@Override
	@ProxyOverride
	public boolean execute(String sql, String[] columnNames)
		throws SQLException {
		checkClose();
		return getStatement().execute(
			connection.getSQL(sql), columnNames);
	}
	
	@Override
	@ProxyOverride
	public QuinaProxyConnection getConnection()
		throws SQLException {
		checkClose();
		return connection;
	}

	@Override
	@ProxyOverride
	public QuinaProxyResultSet getResultSet()
		throws SQLException {
		checkClose();
		return QuinaProxyUtil.getResultSet(
			this, getStatement().getResultSet());
	}
}
